11.ASP.NET Advanced/02. Workshop/CinemaWebApp/Controllers/CinemaController.cs
using CinemaWebApp.Infrastructure.Repositories;
using CinemaWebApp.Infrastructure.Repositories.Contracts;
using CinemaWebApp.Models;
using CinemaWebApp.Models.Data;
using CinemaWebApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query;

namespace CinemaWebApp.Controllers
{
    public class CinemaController : Controller
    {
        private readonly ICinemaRepository repository;
        private readonly ICinemaMovieRepository cinemaMovieRepository;
        private readonly IMovieRepository movieRepository;
        public CinemaController(ICinemaRepository _repository, ICinemaMovieRepository _cinemaMovieRepository, IMovieRepository _movieRepository)
        {
            this.repository = _repository;
            this.cinemaMovieRepository = _cinemaMovieRepository;
            this.movieRepository = _movieRepository;
        }
        public async Task<IActionResult> Index()
        {
            List<Cinema> cinemas = (List<Cinema>)await repository.GetAllAsync();

            IEnumerable<CinemaIndexViewModel> cinemaIndexViewModels = cinemas.Select(c => new CinemaIndexViewModel
            {
                Id = c.Id,
                Name = c.Name,
                Location = c.Location
            });

            return View(cinemaIndexViewModels);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CinemaIndexViewModel cinemaIndexModel)
        {
            if (ModelState.IsValid)
            {
                Cinema cinema = new Cinema
                {
                    Name = cinemaIndexModel.Name,
                    Location = cinemaIndexModel.Location
                };
                await repository.AddAsync(cinema);
                return RedirectToAction("Index");   
            }
            return View(cinemaIndexModel);
        }
        public async Task<IActionResult> Details(int id)
        {
            var cinema = await repository.GetByIdAsync(id);
            var mp = await cinemaMovieRepository.GetAllAsync();

            mp = mp.Where(x => x.CinemaId == id).ToList();

            if(cinema is null)
            {
                return RedirectToAction("Index");
            }

            CinemaDetailsViewModel cinemaDetailsViewModel = new CinemaDetailsViewModel
            {
                Id = cinema.Id,
                Name = cinema.Name,
                Location = cinema.Location,
                Movies = mp.Select(cm=>new MovieProgramViewModel()
                {
                    Title = GetMovieNameAndDurationById(cm.MovieId).Result.Item1,
                    Duration = GetMovieNameAndDurationById(cm.MovieId).Result.Item2,
                }).ToList()
            };

            return View(cinemaDetailsViewModel);
        }
        [HttpGet]
        public async Task<IActionResult> Manage()
        {
            IEnumerable<Cinema> cinemas = (IEnumerable<Cinema>)await repository.GetAllAsync();
            return View(cinemas);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            Cinema cinema = await repository.GetByIdAsync(id);

            EditCinemaViewModel model = new EditCinemaViewModel
            {
                Id = cinema.Id,
                Name = cinema.Name,
                Location = cinema.Location,
            };

            return View(model); 
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>Edit(EditCinemaViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(Manage));
            }
            Cinema cinema = await repository.GetByIdAsync(model.Id);

            cinema.Name = model.Name;
            cinema.Location = model.Location;

            await repository.UpdateAsync(cinema);
            return RedirectToAction(nameof(Manage));
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            Cinema cinema = await repository.GetByIdAsync(id);

            return View(cinema);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Cinema cinema)
        {
            await repository.DeleteAsync(cinema);
            return RedirectToAction(nameof(Manage));
        }
        private async Task<(string,int)> GetMovieNameAndDurationById(int id)
        {
           Movie movie = await movieRepository.GetByIdAsync(id);

            return (movie.Title, movie.Duration);
        }
    }
}

11.ASP.NET Advanced/02. Workshop/CinemaWebApp/Controllers/MovieController.cs
using CinemaWebApp.Infrastructure.Repositories.Contracts;
using CinemaWebApp.Models;
using CinemaWebApp.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CinemaWebApp.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieRepository movieRepostory;
        private readonly ICinemaRepository cinemaRepository;
        private readonly ICinemaMovieRepository cinemaMovieRepository;

        public MovieController(IMovieRepository _repository, ICinemaRepository _cinemaRepository, ICinemaMovieRepository _cinemaMovieRepository)
        {
            this.movieRepostory = _repository;
            this.cinemaRepository = _cinemaRepository;
            this.cinemaMovieRepository = _cinemaMovieRepository;
        }
        public async Task<IActionResult> Index()
        {
            var movies = await movieRepostory.GetAllAsync();
            return View(movies);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View(new MovieViewModel());
        }
        [HttpPost]
        public async Task<IActionResult> Create(MovieViewModel viewModel)
        {
            if (ModelState.IsValid)
            {

                Movie movie = new Movie
                {
                    Title = viewModel.Title,
                    Genre = viewModel.Genre,
                    ReleaseDate = viewModel.ReleaseDate,
                    Director = viewModel.Director,
                    Duration = viewModel.Duration,
                    Description = viewModel.Description,
                    ImageUrl = viewModel.ImageUrl,
                };

                await movieRepostory.AddAsync(movie);

                return RedirectToAction("Index");
            }
            return View(viewModel);
        }
        public async Task<IActionResult> Details(int id)
        {
            Movie? movie = await movieRepostory.GetByIdAsync(id);

            if (movie is null)
            {
                return NotFound();
            }

            return View(movie);
        }
        [HttpGet]
        public async Task<IActionResult> AddToProgram(int movieId)
        {
            Movie? movie = await movieRepostory.GetByIdAsync(movieId);

            if (movie is null)
            {
                return RedirectToAction("Index");
            }

            List<Cinema> cinemas = (List<Cinema>)await cinemaRepository.GetAllAsync();

            AddMovieToCinemaProgramViewModel viewModel = new AddMovieToCinemaProgramViewModel
            {
                MovieId = movie.Id,
                MovieTitle = movie.Title,
                Cinemas = cinemas.Select(c => new CinemaCheckBoxItem
                {
                    Id = c.Id,
                    Name = c.Name,
                    IsSelected = IsSelected(c.Id)
                }).ToList()
            };
            return View(viewModel);
        }
        [HttpPost]
        public async Task<IActionResult> AddToProgram(AddMovieToCinemaProgramViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            List<CinemaMovie> existingAssignments = (List<CinemaMovie>)await cinemaMovieRepository.GetAllAsync();


            existingAssignments = existingAssignments.Where(x => x.MovieId == model.MovieId).ToList();
            foreach (CinemaMovie cm in existingAssignments)
            {
                await cinemaMovieRepository.DeleteAsync(cm);
            }

            foreach (var cinema in model.Cinemas)
            {
                if (cinema.IsSelected)
                {
                    CinemaMovie cinemaMovie = new CinemaMovie
                    {
                        MovieId = model.MovieId,
                        CinemaId = cinema.Id
                    };
                    await cinemaMovieRepository.AddAsync(cinemaMovie);
                }
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Manage()
        {
            IEnumerable<Movie> cinemas = (IEnumerable<Movie>)await movieRepostory.GetAllAsync();
            return View(cinemas);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            Movie movie = await movieRepostory.GetByIdAsync(id);

            EditMovieViewModel model = new EditMovieViewModel
            {
                Id = movie.Id,
                Title = movie.Title,
                Description = movie.Description,
                Director = movie.Director,
                Duration = movie.Duration,
                Genre = movie.Genre,
                ImageUrl = movie.ImageUrl,
                ReleaseDate = movie.ReleaseDate,
            };

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditMovieViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(Manage));
            }
            Movie movie = await movieRepostory.GetByIdAsync(model.Id);

            movie.Title = model.Title;
            movie.Description = model.Description;
            movie.Director = model.Director;
            movie.Duration = model.Duration;
            movie.Genre = model.Genre;
            if(model.ImageUrl is not null)
            {
            movie.ImageUrl = model.ImageUrl;
            }
            movie.ReleaseDate = model.ReleaseDate;

            await movieRepostory.UpdateAsync(movie);

            return RedirectToAction(nameof(Manage));
        }
        [HttpGet]
        public async Task<IActionResult>Delete(int id)
        {
            Movie movie = await movieRepostory.GetByIdAsync(id);
           
            return View(movie);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>Delete(Movie movie)
        {
           await movieRepostory.DeleteAsync(movie);
            return RedirectToAction(nameof(Manage));
        }
        private bool IsSelected(int movieId)
        {
            return cinemaMovieRepository.GetFirstByMovieId(movieId) == null ? false : true;
        }
    }
}

11.ASP.NET Advanced/02. Workshop/CinemaWebApp/Controllers/WatchlistController.cs
using CinemaWebApp.Data.Models;
using CinemaWebApp.Models;
using CinemaWebApp.Models.Data;
using CinemaWebApp.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CinemaWebApp.Controllers
{
    public class WatchlistController:Controller
    {
        private readonly AppDbContext context;
        private readonly UserManager<ApplicationUser> userManager;
        public WatchlistController(AppDbContext context, UserManager<ApplicationUser> userManager)
        {
            this.context = context;
            this.userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            string userId = userManager.GetUserId(User);

           var watchListMovies = await context.UsersMovies
                .Where(um=>um.UserId == userId)
                .Include(um=>um.Movie)
                .Select(um=>new WatchListViewModel
            {
                MovieId = um.MovieId,
                Title = um.Movie.Title,
                Genre = um.Movie.Genre,
                ReleaseDate = um.Movie.ReleaseDate.ToString("MMMM yyyy"),
                ImageUrl = um.Movie.ImageUrl
            }).ToListAsync();

            return View(watchListMovies);
        }
        [HttpPost]
        public async Task<IActionResult> AddToWatchlist(int movieId)
        {
            string userId = userManager.GetUserId(User);

            UserMovie? userMovie = await context.UsersMovies.FirstOrDefaultAsync(x => x.UserId == userId && x.MovieId == movieId);

            if (userMovie == null)
            {
                userMovie = new UserMovie
                {
                    UserId = userId,
                    MovieId = movieId,
                };

                await context.UsersMovies.AddAsync(userMovie);
                await context.SaveChangesAsync();
            }

            return RedirectToAction("Index", "Movie");
        }
        [HttpPost]
        public async Task<IActionResult>RemoveFromWatchlist(int movieId)
        {
            string userId = userManager.GetUserId(User);

            UserMovie? userMovie = await context.UsersMovies.FirstOrDefaultAsync(x => x.UserId == userId && x.MovieId == movieId);

            if(userMovie != null)
            {
                context.UsersMovies.Remove(userMovie);
                await context.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }
    }
}

11.ASP.NET Advanced/02. Workshop/CinemaWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CinemaWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CinemaWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CinemaWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User?.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" id="managerDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Manager
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="managerDropdown">
                                    <li>
                                        <a class="dropdown-item" asp-area="" asp-controller="Cinema" asp-action="Manage">
                                            Manage Cinemas
                                        </a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="" asp-controller="Movie" asp-action="Manage">
                                            Manage Movies
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cinema" asp-action="Index">Cinemas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movies</a>
                        </li>
                        @if (User?.Identity?.IsAuthenticated ?? false)  // Only show if user is logged in
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Watchlist" asp-action="Index">Watchlist</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CinemaWebApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @section Scripts {
        <partial name="_ValidationScriptsPartial" />
    }
</body>
</html>